fra = input('Digite uma frase: ')
fra = fra.strip()
fra = fra.lower()
fra = fra.replace('á', 'a')
fra = fra.replace('à', 'a')
fra = fra.replace('â', 'a')
fra = fra.replace('ã', 'a')
print('Sua frase contém', fra.count('a'),  'letra(s) A.')
print('A posição do primeiro A fica na posição', fra.find('a') + 1)
print('A posição do último A fica na posição', fra.rfind('a') + 1)
