nome = input('Digite seu nome completo: ')
noma = nome.upper()
nomi = nome.lower()
dnome = nome.split()
letras = ''.join(dnome)
print(noma)
print(nomi)
print('Seu nome completo possúi', len(letras), 'letras.')
print('Seu primeiro nome tem', len(dnome[0]), 'letras.')
